DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS does;

CREATE TABLE tasks (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		startDate INTEGER NOT NULL,
		dueDate INTEGER,
		what STRING NOT NULL
		);

CREATE TABLE users (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name STRING NOT NULL,
		email STRING
		);

CREATE TABLE does (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		tasks_id INTEGER NOT NULL,
	        users_id INTEGER NOT NULL
		);	


